.changeset/old-plums-lick.md, base/base.ts, blocks/sharepoint/sharepoint.ts, dist/index.d.ts, dist/index.js, dist/index.mjs, package-lock.json, package.json
Required cbdev PR:
https://bitbucket.org/checkboxtechnology/cbdev/pull-requests/5176
=> DEV-10708: Upload file for sharepoint

blocks/sharepoint/sharepoint.ts, dist/index.js, dist/index.mjs
=> DEV-10707: Implement create folder function for sharepoint

.changeset/afraid-hats-mix.md, blocks/date-calc/date-calc.ts, dist/index.d.ts, dist/index.js, dist/index.mjs
This fixes a bug where the timezone was not being preserved. Variable was converted to UTC time but output was being kept as a UTC time.
=> DEV-10868: Fixed Time Zone Add/Sub

.changeset/thirty-glasses-work.md, base/base.ts, blocks/set-variable/set-variable.ts, dist/index.d.ts, dist/index.js, dist/index.mjs, package-lock.json
=> allow set variable update

.changeset/large-melons-compete.md, blocks/sharepoint/sharepoint.ts, dist/index.js, dist/index.mjs, package-lock.json
[DEV-10830](https://checkboxai.atlassian.net/browse/DEV-10830): To add connection selection
=> Added connection option for sharepoint

.changeset/tidy-avocados-hear.md, base/base.ts, blocks/sharepoint/sharepoint.ts, dist/index.d.ts, dist/index.js, dist/index.mjs
[DEV-10979](https://checkboxai.atlassian.net/browse/DEV-10979): Allow author to control what doc/pdf gets uploaded to Sharepoint
=> DEV-10979: Allow author to control what doc/pdf gets uploaded

.changeset/sweet-tables-shave.md, blocks/date-calc/date-calc.ts, blocks/set-variable/set-variable.ts, blocks/triage/triage.ts, dist/index.js, dist/index.mjs
[DEV-11106](https://checkboxai.atlassian.net/browse/DEV-11106): Set_variable allows for space in variable name
=> DEV-11106: Set_variable allows for space in variable name

blocks/sharepoint/sharepoint.ts, dist/index.js, dist/index.mjs
[DEV-11160](https://checkboxai.atlassian.net/browse/DEV-11160): SharePoint : Uploaded file not displayed in SharePoint if we don't select any file type
[DEV-11159](https://checkboxai.atlassian.net/browse/DEV-11159): SharePoint : Error displayed & user can't move forward from SharePoint block
=> DEV-11160,DEV-11159: at least one file type and handle empty of prefix

.changeset/gorgeous-ties-battle.md, base/base.ts, blocks/sharepoint/sharepoint.ts, dist/index.d.ts, dist/index.js, dist/index.mjs
- Allow function in showIf
- Skip .pdf.docx upload because it is corrupted
=> DEV-11174,DEV-11172,DEV-11160: Sharepoint bugs

.changeset/seven-gifts-remember.md, blocks/date-calc/date-calc.ts, blocks/set-variable/set-variable.ts, blocks/triage/triage.ts, dist/index.js, dist/index.mjs
Variable input should be alphanumeric and start with alphabet
=> DEV-11106: follow golang validation for static variable name

.changeset/silly-maps-brush.md, blocks/sharepoint/sharepoint.ts, dist/index.js, dist/index.mjs
Issue: https://checkboxai.atlassian.net/browse/DEV-11174?focusedCommentId=31588
=> DEV-11174: Application only uploading Docx & PDF file in SharePoint

.changeset/grumpy-jeans-glow.md, blocks/date-calc/date-calc.ts, dist/index.js, dist/index.mjs, package-lock.json
Widget flattening SQS queue keep retrying due to invalid date error
=> DEV-11688: Widgets takes a long time to load assessment data during Bulk Import

.changeset/ninety-nails-lay.md, blocks/sharepoint/sharepoint.ts, dist/index.js, dist/index.mjs
https://checkboxai.atlassian.net/browse/DEV-11875
```
Looks like we don't support multiple SP instances. I added our SP to Qualitas's env and this is what i get in the property editor[Edson Wu: Btw Yang Pan looks like we don't support multiple SP instances.
```
=> DEV-11875: Sharepoint integration should support multiple SP instances

.changeset/calm-ghosts-notice.md, base/base.ts, blocks/ticket/ticket.ts, dist/index.d.ts, dist/index.js, dist/index.mjs
Add runtime to ticketing block.
- validate ticket fields
- create ticket with fields
- create ticket message
=> DEV-11943 add runtime to ticketing block

.changeset/grumpy-snails-arrive.md, base/base.ts, blocks/set-variable/set-variable.ts, blocks/set-variable/timezones.json, blocks/sharepoint/sharepoint.ts, dist/index.d.ts, dist/index.js, dist/index.mjs, tsconfig.json
Also has some basic stuff for format date variable inside however the option is commented out
=> Added in RAD and Checkbox input to set variable

.changeset/moody-geese-watch.md, base/base.ts, blocks/set-variable/set-variable.ts, dist/index.d.ts, dist/index.js, dist/index.mjs
How it works
http://recordit.co/VdskbxrWyt
=> [DEV-11991] Support variable input for doc variables on SET_VAR

.changeset/tough-bikes-learn.md, blocks/set-variable/set-variable.ts, dist/index.js, dist/index.mjs
DEV-11991: Causing trouble to this-
https://checkboxai.atlassian.net/browse/DEV-12157
So set `new template` as default
=> DEV-11991: Changed default checked value to match existing data

.changeset/tender-apes-taste.md, blocks/ticket/ticket.ts, dist/index.js, dist/index.mjs
https://bitbucket.org/checkboxtechnology/cbdev/pull-requests/6311
Add new param to create ticket message endpoint
=> DEV-12288-create ticket message endpoint new param message type

.changeset/brave-ways-smash.md, blocks/ticket/ticket.ts, dist/index.js, dist/index.mjs
`block_description` must be outside of group to work
=> DEV-12493: fix ticketing block description not showing on ui

.changeset/witty-jars-help.md, blocks/sharepoint/sharepoint.ts, dist/index.js, dist/index.mjs
fix if statement check on DOC sharepoint upload
=> DEV-12691: fix file type checking on DOC type sharepoint

.changeset/flat-peas-attend.md, blocks/sharepoint/sharepoint.ts, dist/index.js, dist/index.mjs, package-lock.json
remove duplicated cbk console log for parsedFile
=> DEV-12691: remove duplicated cbk console log

.changeset/purple-crabs-doubt.md, blocks/set-variable/set-variable.ts, dist/index.js, dist/index.mjs
https://www.loom.com/share/ab6717e9b4f9431bb74c902fd1046c64?sid=1c4979db-013b-4b92-a16a-a6f1fe01e3d8
Allow variable input for num variable in set var
https://checkboxai.atlassian.net/browse/DEV-12777
=> DEV-12777: set var block num input allow variables

.changeset/weak-panthers-confess.md, blocks/ticket/ticket.ts, dist/index.js, dist/index.mjs
https://checkboxai.atlassian.net/browse/DEV-13263
Update cbk to use new service function for Multi-thread flow
=> DEV-13262: Update create message to consume new service and function

.changeset/popular-dolphins-walk.md, blocks/ticket/ticket.ts, dist/index.js, dist/index.mjs
https://checkboxai.atlassian.net/browse/DEV-13640
=> DEV-13640: Fix main thread label for matter created via cbk

blocks/ticket/ticket.ts, blocks/ticket/utils.ts, dist/index.js, dist/index.mjs
https://checkboxai.atlassian.net/browse/DEV-13671
When a ticket is created in workflow, if the variable is not initialised, the ticket create experience fails
=> DEV-13671 ignore non-initialised variables

.changeset/shiny-icons-push.md, .changeset/tame-rivers-add.md, package-lock.json
=> DEV-13671 changeset

.changeset/green-chicken-lay.md, blocks/ticket/ticket.ts, dist/index.js, dist/index.mjs
https://checkboxai.atlassian.net/browse/DEV-13961
=> DEV-13961 WF status

.changeset/late-coats-mate.md, blocks/ticket/ticket.ts, dist/index.js, dist/index.mjs
https://checkboxai.atlassian.net/browse/DEV-14250
=> DEV-14250 remove pdf version of docx from files tab

.changeset/late-coats-mate.md, .changeset/tasty-planets-smash.md, blocks/ticket/ticket.ts, dist/index.js, dist/index.mjs
https://checkboxai.atlassian.net/browse/DEV-14250
https://jam.dev/c/6e435ea5-28a4-4666-a1e0-651f311b074f
From 'File Upload' the file data returned:
{
fileKey: '0247b73a-16f2-4729-b5c3-c1d822fff489',
fileName: '123.pdf',
publicKey: '50901144-8d29-4658-afb3-18fd8a491681'
}
For 'Doc Upload' the file data returned:
{
reportName: 'file-sample_150kB.pdf',
fileName: 'file-sample_150kB.docx',
fileKey: '170c41ed-b7a7-4737-93a0-35691b1bcbde',
publicKey: '29dc0ea3-260f-43f9-a616-2d32f7529930',
fileType: 'report',
documentId: 'd6c902d4-25dc-4d04-ac11-a5cc1326721e',
documentVersionId: '1294ea10-d6f5-4df3-97a0-254a8f88bd15'
},
{
reportName: 'file-sample_150kB.pdf',
fileName: 'file-sample_150kB.pdf',
fileKey: '170c41ed-b7a7-4737-93a0-35691b1bcbde',
publicKey: '29dc0ea3-260f-43f9-a616-2d32f7529930', …
=> DEV-14250 Fix Bugs from filtering out generated PDF from Doc upload

.changeset/nine-schools-sell.md
Changes here: https://github.com/CheckboxAI/custom-block-kit/pull/199
=> Updated changeset
